%%
tau_min_para = subs(tau_stdard_para,  ...
              {'Ixx1', 'Ixx2', 'Ixx3', 'Ixx4', 'Ixx5', 'Ixx6',  ...
	           'Ixy1', 'Ixy2', 'Ixy3', 'Ixy4', 'Ixy5', 'Ixy6',  ...
	           'Ixz1', 'Ixz2', 'Ixz3', 'Ixz4', 'Ixz5', 'Ixz6',  ...
	           'Iyy1', 'Iyy2', 'Iyy3', 'Iyy4', 'Iyy5', 'Iyy6',  ...
	           'Iyz1', 'Iyz2', 'Iyz3', 'Iyz4', 'Iyz5', 'Iyz6',  ...
	           'Izz1', 'Izz2', 'Izz3', 'Izz4', 'Izz5', 'Izz6'}, ...
              {xx1, xx2, xx3, xx4, xx5, xx6,  ...
	           xy1, xy2, xy3, xy4, xy5, xy6,  ...
	           xz1, xz2, xz3, xz4, xz5, xz6,  ...
	           yy1, yy2, yy3, yy4, yy5, yy6,  ...
	           yz1, yz2, yz3, yz4, yz5, yz6,  ...
	           zz1, zz2, zz3, zz4, zz5, zz6});
%%

Y = tau_min_para*pinv(pmin);
assignin('base', 'Y', Y);
matlabFunction(Y,'File','Y_function',...
               'Vars',{q,qd,qdd});
